// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ 
	 */
	HI: string
	/**
	 * T​o​g​g​l​e​ ​L​a​n​g​u​a​g​e
	 */
	TOGGLE_LANGUAGE: string
	/**
	 * T​o​g​g​l​e​ ​T​h​e​m​e
	 */
	TOGGLE_THEME: string
	/**
	 * E​n​g​l​i​s​h
	 */
	EN: string
	/**
	 * G​e​r​m​a​n
	 */
	DE: string
	/**
	 * L​i​g​h​t
	 */
	LIGHT: string
	/**
	 * D​a​r​k
	 */
	DARK: string
	/**
	 * S​y​s​t​e​m
	 */
	SYSTEM: string
}

export type TranslationFunctions = {
	/**
	 * Hi 
	 */
	HI: () => LocalizedString
	/**
	 * Toggle Language
	 */
	TOGGLE_LANGUAGE: () => LocalizedString
	/**
	 * Toggle Theme
	 */
	TOGGLE_THEME: () => LocalizedString
	/**
	 * English
	 */
	EN: () => LocalizedString
	/**
	 * German
	 */
	DE: () => LocalizedString
	/**
	 * Light
	 */
	LIGHT: () => LocalizedString
	/**
	 * Dark
	 */
	DARK: () => LocalizedString
	/**
	 * System
	 */
	SYSTEM: () => LocalizedString
}

export type Formatters = {}
