// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​a​l​l​o
	 */
	HI: string
	/**
	 * H​a​l​l​o
	 */
	AXS: string
}

export type TranslationFunctions = {
	/**
	 * Hallo
	 */
	HI: () => LocalizedString
	/**
	 * Hallo
	 */
	AXS: () => LocalizedString
}

export type Formatters = {}
