/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { customFetch } from "./lib/custom-fetch";
export type GetApiByGuildIdStaff200ItemGlobalName = string | null;

export type GetApiByGuildIdStaff200ItemNickname = string | null;

export type GetApiByGuildIdStaff200ItemDisplayName = string | null;

export type GetApiByGuildIdStaff200ItemBannerUrl = string | null;

export type GetApiByGuildIdStaff200ItemAccentColor = number | null;

export type GetApiByGuildIdStaff200ItemFlags = string | null;

export type GetApiByGuildIdStaff200ItemCollectibles = string | null;

export type GetApiByGuildIdStaff200ItemPrimaryGuild = string | null;

export type GetApiByGuildIdStaff200ItemRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdStaff200ItemActivity = string | null;

export type GetApiByGuildIdStaff200ItemPresenceUpdatedAt = string | null;

export type GetApiByGuildIdStaff200ItemPremiumSince = string | null;

export type GetApiByGuildIdStaff200ItemCommunicationDisabledUntil =
  | string
  | null;

export type GetApiByGuildIdStaff200ItemJoinedAt = string | null;

export type GetApiByGuildIdStaff200ItemUpdatedAt = string | null;

export type GetApiByGuildIdStaff200Item = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdStaff200ItemGlobalName;
  nickname: GetApiByGuildIdStaff200ItemNickname;
  displayName: GetApiByGuildIdStaff200ItemDisplayName;
  avatarUrl: string;
  bannerUrl: GetApiByGuildIdStaff200ItemBannerUrl;
  accentColor: GetApiByGuildIdStaff200ItemAccentColor;
  displayHexColor: string;
  flags: GetApiByGuildIdStaff200ItemFlags;
  collectibles: GetApiByGuildIdStaff200ItemCollectibles;
  primaryGuild: GetApiByGuildIdStaff200ItemPrimaryGuild;
  roles: GetApiByGuildIdStaff200ItemRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdStaff200ItemActivity;
  presenceUpdatedAt: GetApiByGuildIdStaff200ItemPresenceUpdatedAt;
  premiumSince: GetApiByGuildIdStaff200ItemPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdStaff200ItemCommunicationDisabledUntil;
  joinedAt: GetApiByGuildIdStaff200ItemJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdStaff200ItemUpdatedAt;
};

export type GetApiByGuildIdStaff422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdNews200ItemAuthorGlobalName = string | null;

export type GetApiByGuildIdNews200ItemAuthorNickname = string | null;

export type GetApiByGuildIdNews200ItemAuthorDisplayName = string | null;

export type GetApiByGuildIdNews200ItemAuthorBannerUrl = string | null;

export type GetApiByGuildIdNews200ItemAuthorAccentColor = number | null;

export type GetApiByGuildIdNews200ItemAuthorFlags = string | null;

export type GetApiByGuildIdNews200ItemAuthorCollectibles = string | null;

export type GetApiByGuildIdNews200ItemAuthorPrimaryGuild = string | null;

export type GetApiByGuildIdNews200ItemAuthorRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdNews200ItemAuthorActivity = string | null;

export type GetApiByGuildIdNews200ItemAuthorPresenceUpdatedAt = string | null;

export type GetApiByGuildIdNews200ItemAuthorPremiumSince = string | null;

export type GetApiByGuildIdNews200ItemAuthorCommunicationDisabledUntil =
  | string
  | null;

export type GetApiByGuildIdNews200ItemAuthorJoinedAt = string | null;

export type GetApiByGuildIdNews200ItemAuthorUpdatedAt = string | null;

export type GetApiByGuildIdNews200ItemAuthor = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdNews200ItemAuthorGlobalName;
  nickname: GetApiByGuildIdNews200ItemAuthorNickname;
  displayName: GetApiByGuildIdNews200ItemAuthorDisplayName;
  avatarUrl: string;
  bannerUrl: GetApiByGuildIdNews200ItemAuthorBannerUrl;
  accentColor: GetApiByGuildIdNews200ItemAuthorAccentColor;
  displayHexColor: string;
  flags: GetApiByGuildIdNews200ItemAuthorFlags;
  collectibles: GetApiByGuildIdNews200ItemAuthorCollectibles;
  primaryGuild: GetApiByGuildIdNews200ItemAuthorPrimaryGuild;
  roles: GetApiByGuildIdNews200ItemAuthorRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdNews200ItemAuthorActivity;
  presenceUpdatedAt: GetApiByGuildIdNews200ItemAuthorPresenceUpdatedAt;
  premiumSince: GetApiByGuildIdNews200ItemAuthorPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdNews200ItemAuthorCommunicationDisabledUntil;
  joinedAt: GetApiByGuildIdNews200ItemAuthorJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdNews200ItemAuthorUpdatedAt;
};

export type GetApiByGuildIdNews200ItemEditedAt = string | null;

export type GetApiByGuildIdNews200ItemAttachmentsItemDescription =
  | string
  | null;

export type GetApiByGuildIdNews200ItemAttachmentsItemContentType =
  | string
  | null;

export type GetApiByGuildIdNews200ItemAttachmentsItemWidth = number | null;

export type GetApiByGuildIdNews200ItemAttachmentsItemHeight = number | null;

export type GetApiByGuildIdNews200ItemAttachmentsItemDuration = number | null;

export type GetApiByGuildIdNews200ItemAttachmentsItemWaveform = string | null;

export type GetApiByGuildIdNews200ItemAttachmentsItemFlags = string | null;

export type GetApiByGuildIdNews200ItemAttachmentsItem = {
  id: string;
  url: string;
  proxyURL: string;
  name: string;
  description: GetApiByGuildIdNews200ItemAttachmentsItemDescription;
  contentType: GetApiByGuildIdNews200ItemAttachmentsItemContentType;
  size: number;
  width: GetApiByGuildIdNews200ItemAttachmentsItemWidth;
  height: GetApiByGuildIdNews200ItemAttachmentsItemHeight;
  ephemeral: boolean;
  duration: GetApiByGuildIdNews200ItemAttachmentsItemDuration;
  waveform: GetApiByGuildIdNews200ItemAttachmentsItemWaveform;
  flags: GetApiByGuildIdNews200ItemAttachmentsItemFlags;
};

export type GetApiByGuildIdNews200ItemEmbedsItemTitle = string | null;

export type GetApiByGuildIdNews200ItemEmbedsItemDescription = string | null;

export type GetApiByGuildIdNews200ItemEmbedsItemUrl = string | null;

export type GetApiByGuildIdNews200ItemEmbedsItemColor = number | null;

export type GetApiByGuildIdNews200ItemEmbedsItemTimestamp = string | null;

export type GetApiByGuildIdNews200ItemEmbedsItemFieldsItemInline =
  | boolean
  | unknown;

export type GetApiByGuildIdNews200ItemEmbedsItemFieldsItem = {
  name: string;
  value: string;
  inline: GetApiByGuildIdNews200ItemEmbedsItemFieldsItemInline;
};

export type GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOfUrl = string | null;

export type GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOfIconURL =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOfProxyIconURL =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOf = {
  name: string;
  url: GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOfUrl;
  iconURL: GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOfIconURL;
  proxyIconURL: GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOfProxyIconURL;
};

export type GetApiByGuildIdNews200ItemEmbedsItemAuthor =
  GetApiByGuildIdNews200ItemEmbedsItemAuthorAnyOf | null;

export type GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOfProxyURL =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOfWidth =
  | number
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOfHeight =
  | number
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOf = {
  url: string;
  proxyURL: GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOfProxyURL;
  width: GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOfWidth;
  height: GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOfHeight;
};

export type GetApiByGuildIdNews200ItemEmbedsItemThumbnail =
  GetApiByGuildIdNews200ItemEmbedsItemThumbnailAnyOf | null;

export type GetApiByGuildIdNews200ItemEmbedsItemImageAnyOfProxyURL =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemImageAnyOfWidth = number | null;

export type GetApiByGuildIdNews200ItemEmbedsItemImageAnyOfHeight =
  | number
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemImageAnyOf = {
  url: string;
  proxyURL: GetApiByGuildIdNews200ItemEmbedsItemImageAnyOfProxyURL;
  width: GetApiByGuildIdNews200ItemEmbedsItemImageAnyOfWidth;
  height: GetApiByGuildIdNews200ItemEmbedsItemImageAnyOfHeight;
};

export type GetApiByGuildIdNews200ItemEmbedsItemImage =
  GetApiByGuildIdNews200ItemEmbedsItemImageAnyOf | null;

export type GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfUrl = string | null;

export type GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfProxyURL =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfWidth = number | null;

export type GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfHeight =
  | number
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOf = {
  url: GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfUrl;
  proxyURL: GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfProxyURL;
  width: GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfWidth;
  height: GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOfHeight;
};

export type GetApiByGuildIdNews200ItemEmbedsItemVideo =
  GetApiByGuildIdNews200ItemEmbedsItemVideoAnyOf | null;

export type GetApiByGuildIdNews200ItemEmbedsItemFooterAnyOfIconURL =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemFooterAnyOfProxyIconURL =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemFooterAnyOf = {
  text: string;
  iconURL: GetApiByGuildIdNews200ItemEmbedsItemFooterAnyOfIconURL;
  proxyIconURL: GetApiByGuildIdNews200ItemEmbedsItemFooterAnyOfProxyIconURL;
};

export type GetApiByGuildIdNews200ItemEmbedsItemFooter =
  GetApiByGuildIdNews200ItemEmbedsItemFooterAnyOf | null;

export type GetApiByGuildIdNews200ItemEmbedsItemProviderAnyOfName =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemProviderAnyOfUrl =
  | string
  | null;

export type GetApiByGuildIdNews200ItemEmbedsItemProviderAnyOf = {
  name: GetApiByGuildIdNews200ItemEmbedsItemProviderAnyOfName;
  url: GetApiByGuildIdNews200ItemEmbedsItemProviderAnyOfUrl;
};

export type GetApiByGuildIdNews200ItemEmbedsItemProvider =
  GetApiByGuildIdNews200ItemEmbedsItemProviderAnyOf | null;

export type GetApiByGuildIdNews200ItemEmbedsItem = {
  title: GetApiByGuildIdNews200ItemEmbedsItemTitle;
  description: GetApiByGuildIdNews200ItemEmbedsItemDescription;
  url: GetApiByGuildIdNews200ItemEmbedsItemUrl;
  color: GetApiByGuildIdNews200ItemEmbedsItemColor;
  timestamp: GetApiByGuildIdNews200ItemEmbedsItemTimestamp;
  fields: GetApiByGuildIdNews200ItemEmbedsItemFieldsItem[];
  author: GetApiByGuildIdNews200ItemEmbedsItemAuthor;
  thumbnail: GetApiByGuildIdNews200ItemEmbedsItemThumbnail;
  image: GetApiByGuildIdNews200ItemEmbedsItemImage;
  video: GetApiByGuildIdNews200ItemEmbedsItemVideo;
  footer: GetApiByGuildIdNews200ItemEmbedsItemFooter;
  provider: GetApiByGuildIdNews200ItemEmbedsItemProvider;
};

export type GetApiByGuildIdNews200ItemMentionsUsersItemGlobalName =
  | string
  | null;

export type GetApiByGuildIdNews200ItemMentionsUsersItem = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdNews200ItemMentionsUsersItemGlobalName;
};

export type GetApiByGuildIdNews200ItemMentionsRolesItem = {
  id: string;
  name: string;
};

export type GetApiByGuildIdNews200ItemMentions = {
  users: GetApiByGuildIdNews200ItemMentionsUsersItem[];
  roles: GetApiByGuildIdNews200ItemMentionsRolesItem[];
  everyone: boolean;
};

export type GetApiByGuildIdNews200ItemReactionsItemEmojiId = string | null;

export type GetApiByGuildIdNews200ItemReactionsItemEmojiName = string | null;

export type GetApiByGuildIdNews200ItemReactionsItemEmoji = {
  id: GetApiByGuildIdNews200ItemReactionsItemEmojiId;
  name: GetApiByGuildIdNews200ItemReactionsItemEmojiName;
};

export type GetApiByGuildIdNews200ItemReactionsItem = {
  emoji: GetApiByGuildIdNews200ItemReactionsItemEmoji;
  count: number;
};

export type GetApiByGuildIdNews200ItemReferenceAnyOfMessageId = string | null;

export type GetApiByGuildIdNews200ItemReferenceAnyOfGuildId = string | null;

export type GetApiByGuildIdNews200ItemReferenceAnyOf = {
  messageId: GetApiByGuildIdNews200ItemReferenceAnyOfMessageId;
  channelId: string;
  guildId: GetApiByGuildIdNews200ItemReferenceAnyOfGuildId;
};

export type GetApiByGuildIdNews200ItemReference =
  GetApiByGuildIdNews200ItemReferenceAnyOf | null;

export type GetApiByGuildIdNews200Item = {
  author: GetApiByGuildIdNews200ItemAuthor;
  id: string;
  content: string;
  createdAt: string;
  editedAt: GetApiByGuildIdNews200ItemEditedAt;
  pinned: boolean;
  tts: boolean;
  type: string;
  attachments: GetApiByGuildIdNews200ItemAttachmentsItem[];
  embeds: GetApiByGuildIdNews200ItemEmbedsItem[];
  mentions: GetApiByGuildIdNews200ItemMentions;
  reactions: GetApiByGuildIdNews200ItemReactionsItem[];
  reference: GetApiByGuildIdNews200ItemReference;
};

export type GetApiByGuildIdNews422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdWidget200MembersItemGlobalName = string | null;

export type GetApiByGuildIdWidget200MembersItemNickname = string | null;

export type GetApiByGuildIdWidget200MembersItemDisplayName = string | null;

export type GetApiByGuildIdWidget200MembersItemBannerUrl = string | null;

export type GetApiByGuildIdWidget200MembersItemAccentColor = number | null;

export type GetApiByGuildIdWidget200MembersItemFlags = string | null;

export type GetApiByGuildIdWidget200MembersItemCollectibles = string | null;

export type GetApiByGuildIdWidget200MembersItemPrimaryGuild = string | null;

export type GetApiByGuildIdWidget200MembersItemRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdWidget200MembersItemActivity = string | null;

export type GetApiByGuildIdWidget200MembersItemPresenceUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdWidget200MembersItemPremiumSince = string | null;

export type GetApiByGuildIdWidget200MembersItemCommunicationDisabledUntil =
  | string
  | null;

export type GetApiByGuildIdWidget200MembersItemJoinedAt = string | null;

export type GetApiByGuildIdWidget200MembersItemUpdatedAt = string | null;

export type GetApiByGuildIdWidget200MembersItem = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdWidget200MembersItemGlobalName;
  nickname: GetApiByGuildIdWidget200MembersItemNickname;
  displayName: GetApiByGuildIdWidget200MembersItemDisplayName;
  avatarUrl: string;
  bannerUrl: GetApiByGuildIdWidget200MembersItemBannerUrl;
  accentColor: GetApiByGuildIdWidget200MembersItemAccentColor;
  displayHexColor: string;
  flags: GetApiByGuildIdWidget200MembersItemFlags;
  collectibles: GetApiByGuildIdWidget200MembersItemCollectibles;
  primaryGuild: GetApiByGuildIdWidget200MembersItemPrimaryGuild;
  roles: GetApiByGuildIdWidget200MembersItemRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdWidget200MembersItemActivity;
  presenceUpdatedAt: GetApiByGuildIdWidget200MembersItemPresenceUpdatedAt;
  premiumSince: GetApiByGuildIdWidget200MembersItemPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdWidget200MembersItemCommunicationDisabledUntil;
  joinedAt: GetApiByGuildIdWidget200MembersItemJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdWidget200MembersItemUpdatedAt;
};

export type GetApiByGuildIdWidget200IconURL = string | null;

export type GetApiByGuildIdWidget200BannerURL = string | null;

export type GetApiByGuildIdWidget200 = {
  id: string;
  name: string;
  members: GetApiByGuildIdWidget200MembersItem[];
  presenceCount: number;
  memberCount: number;
  iconURL: GetApiByGuildIdWidget200IconURL;
  bannerURL: GetApiByGuildIdWidget200BannerURL;
};

export type GetApiByGuildIdWidget422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdBoardByBoardType200ItemBoardType =
  (typeof GetApiByGuildIdBoardByBoardType200ItemBoardType)[keyof typeof GetApiByGuildIdBoardByBoardType200ItemBoardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiByGuildIdBoardByBoardType200ItemBoardType = {
  "job-board": "job-board",
  "dev-board": "dev-board",
  showcase: "showcase",
} as const;

export type GetApiByGuildIdBoardByBoardType200ItemParentId = string | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorGlobalName =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorNickname =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorDisplayName =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorBannerUrl =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAccentColor =
  | number
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorFlags = string | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorCollectibles =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorPrimaryGuild =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdBoardByBoardType200ItemAuthorActivity =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorPresenceUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorPremiumSince =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorCommunicationDisabledUntil =
  string | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorJoinedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthor = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdBoardByBoardType200ItemAuthorGlobalName;
  nickname: GetApiByGuildIdBoardByBoardType200ItemAuthorNickname;
  displayName: GetApiByGuildIdBoardByBoardType200ItemAuthorDisplayName;
  avatarUrl: string;
  bannerUrl: GetApiByGuildIdBoardByBoardType200ItemAuthorBannerUrl;
  accentColor: GetApiByGuildIdBoardByBoardType200ItemAuthorAccentColor;
  displayHexColor: string;
  flags: GetApiByGuildIdBoardByBoardType200ItemAuthorFlags;
  collectibles: GetApiByGuildIdBoardByBoardType200ItemAuthorCollectibles;
  primaryGuild: GetApiByGuildIdBoardByBoardType200ItemAuthorPrimaryGuild;
  roles: GetApiByGuildIdBoardByBoardType200ItemAuthorRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdBoardByBoardType200ItemAuthorActivity;
  presenceUpdatedAt: GetApiByGuildIdBoardByBoardType200ItemAuthorPresenceUpdatedAt;
  premiumSince: GetApiByGuildIdBoardByBoardType200ItemAuthorPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdBoardByBoardType200ItemAuthorCommunicationDisabledUntil;
  joinedAt: GetApiByGuildIdBoardByBoardType200ItemAuthorJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdBoardByBoardType200ItemAuthorUpdatedAt;
};

export type GetApiByGuildIdBoardByBoardType200ItemCreatedAt = string | null;

export type GetApiByGuildIdBoardByBoardType200ItemTagsItemEmojiId =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemTagsItemEmojiName =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemTagsItemEmoji = {
  id: GetApiByGuildIdBoardByBoardType200ItemTagsItemEmojiId;
  name: GetApiByGuildIdBoardByBoardType200ItemTagsItemEmojiName;
};

export type GetApiByGuildIdBoardByBoardType200ItemTagsItem = {
  id: string;
  name: string;
  emoji: GetApiByGuildIdBoardByBoardType200ItemTagsItemEmoji;
};

export type GetApiByGuildIdBoardByBoardType200ItemContent = string | null;

export type GetApiByGuildIdBoardByBoardType200ItemImageUrl = string | null;

export type GetApiByGuildIdBoardByBoardType200ItemArchivedAt = string | null;

export type GetApiByGuildIdBoardByBoardType200ItemAutoArchiveDuration =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemInvitable = boolean | null;

export type GetApiByGuildIdBoardByBoardType200ItemRateLimitPerUser =
  | number
  | null;

export type GetApiByGuildIdBoardByBoardType200Item = {
  id: string;
  name: string;
  boardType: GetApiByGuildIdBoardByBoardType200ItemBoardType;
  parentId: GetApiByGuildIdBoardByBoardType200ItemParentId;
  author: GetApiByGuildIdBoardByBoardType200ItemAuthor;
  createdAt: GetApiByGuildIdBoardByBoardType200ItemCreatedAt;
  tags: GetApiByGuildIdBoardByBoardType200ItemTagsItem[];
  content: GetApiByGuildIdBoardByBoardType200ItemContent;
  imageUrl: GetApiByGuildIdBoardByBoardType200ItemImageUrl;
  messageCount: number;
  totalMessageSent: number;
  memberCount: number;
  locked: boolean;
  archived: boolean;
  archivedAt: GetApiByGuildIdBoardByBoardType200ItemArchivedAt;
  autoArchiveDuration: GetApiByGuildIdBoardByBoardType200ItemAutoArchiveDuration;
  invitable: GetApiByGuildIdBoardByBoardType200ItemInvitable;
  rateLimitPerUser: GetApiByGuildIdBoardByBoardType200ItemRateLimitPerUser;
  flags: number;
};

export type GetApiByGuildIdBoardByBoardType422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadIdParams = {
  before?: string;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadBoardType =
  (typeof GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadBoardType)[keyof typeof GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadBoardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadBoardType = {
  "job-board": "job-board",
  "dev-board": "dev-board",
  showcase: "showcase",
} as const;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadParentId =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorGlobalName =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorNickname =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorDisplayName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorBannerUrl =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorAccentColor =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorFlags =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorCollectibles =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorPrimaryGuild =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorRolesItem =
  {
    name: string;
    position: number;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorActivity =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorPresenceUpdatedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorPremiumSince =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorCommunicationDisabledUntil =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorJoinedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthor = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorGlobalName;
  nickname: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorNickname;
  displayName: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorDisplayName;
  avatarUrl: string;
  bannerUrl: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorBannerUrl;
  accentColor: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorAccentColor;
  displayHexColor: string;
  flags: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorFlags;
  collectibles: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorCollectibles;
  primaryGuild: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorPrimaryGuild;
  roles: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorActivity;
  presenceUpdatedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorPresenceUpdatedAt;
  premiumSince: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorCommunicationDisabledUntil;
  joinedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthorUpdatedAt;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadCreatedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItemEmojiId =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItemEmojiName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItemEmoji = {
  id: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItemEmojiId;
  name: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItemEmojiName;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItem = {
  id: string;
  name: string;
  emoji: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItemEmoji;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadContent =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadImageUrl =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadArchivedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAutoArchiveDuration =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadInvitable =
  | boolean
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadRateLimitPerUser =
  | number
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200Thread = {
  id: string;
  name: string;
  boardType: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadBoardType;
  parentId: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadParentId;
  author: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAuthor;
  createdAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadCreatedAt;
  tags: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadTagsItem[];
  content: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadContent;
  imageUrl: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadImageUrl;
  messageCount: number;
  totalMessageSent: number;
  memberCount: number;
  locked: boolean;
  archived: boolean;
  archivedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadArchivedAt;
  autoArchiveDuration: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadAutoArchiveDuration;
  invitable: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadInvitable;
  rateLimitPerUser: GetApiByGuildIdBoardByBoardTypeByThreadId200ThreadRateLimitPerUser;
  flags: number;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorGlobalName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorNickname =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorDisplayName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorBannerUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorAccentColor =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorFlags =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorCollectibles =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorPrimaryGuild =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorRolesItem =
  {
    name: string;
    position: number;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorActivity =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorPresenceUpdatedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorPremiumSince =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorCommunicationDisabledUntil =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorJoinedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorUpdatedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthor = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorGlobalName;
  nickname: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorNickname;
  displayName: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorDisplayName;
  avatarUrl: string;
  bannerUrl: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorBannerUrl;
  accentColor: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorAccentColor;
  displayHexColor: string;
  flags: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorFlags;
  collectibles: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorCollectibles;
  primaryGuild: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorPrimaryGuild;
  roles: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorActivity;
  presenceUpdatedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorPresenceUpdatedAt;
  premiumSince: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorCommunicationDisabledUntil;
  joinedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthorUpdatedAt;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEditedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemDescription =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemContentType =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemWidth =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemHeight =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemDuration =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemWaveform =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemFlags =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItem =
  {
    id: string;
    url: string;
    proxyURL: string;
    name: string;
    description: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemDescription;
    contentType: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemContentType;
    size: number;
    width: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemWidth;
    height: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemHeight;
    ephemeral: boolean;
    duration: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemDuration;
    waveform: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemWaveform;
    flags: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItemFlags;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemTitle =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemDescription =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemColor =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemTimestamp =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFieldsItemInline =
  boolean | unknown;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFieldsItem =
  {
    name: string;
    value: string;
    inline: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFieldsItemInline;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOfUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOfIconURL =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOfProxyIconURL =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOf =
  {
    name: string;
    url: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOfUrl;
    iconURL: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOfIconURL;
    proxyIconURL: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOfProxyIconURL;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthor =
  GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthorAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOfProxyURL =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOfWidth =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOfHeight =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOf =
  {
    url: string;
    proxyURL: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOfProxyURL;
    width: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOfWidth;
    height: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOfHeight;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnail =
  GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnailAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOfProxyURL =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOfWidth =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOfHeight =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOf =
  {
    url: string;
    proxyURL: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOfProxyURL;
    width: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOfWidth;
    height: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOfHeight;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImage =
  GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImageAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfProxyURL =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfWidth =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfHeight =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOf =
  {
    url: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfUrl;
    proxyURL: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfProxyURL;
    width: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfWidth;
    height: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOfHeight;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideo =
  GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideoAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooterAnyOfIconURL =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooterAnyOfProxyIconURL =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooterAnyOf =
  {
    text: string;
    iconURL: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooterAnyOfIconURL;
    proxyIconURL: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooterAnyOfProxyIconURL;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooter =
  GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooterAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProviderAnyOfName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProviderAnyOfUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProviderAnyOf =
  {
    name: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProviderAnyOfName;
    url: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProviderAnyOfUrl;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProvider =
  GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProviderAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItem =
  {
    title: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemTitle;
    description: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemDescription;
    url: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemUrl;
    color: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemColor;
    timestamp: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemTimestamp;
    fields: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFieldsItem[];
    author: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemAuthor;
    thumbnail: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemThumbnail;
    image: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemImage;
    video: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemVideo;
    footer: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemFooter;
    provider: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItemProvider;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentionsUsersItemGlobalName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentionsUsersItem =
  {
    id: string;
    username: string;
    globalName: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentionsUsersItemGlobalName;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentionsRolesItem =
  {
    id: string;
    name: string;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentions = {
  users: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentionsUsersItem[];
  roles: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentionsRolesItem[];
  everyone: boolean;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItemEmojiId =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItemEmojiName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItemEmoji =
  {
    id: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItemEmojiId;
    name: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItemEmojiName;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItem =
  {
    emoji: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItemEmoji;
    count: number;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReferenceAnyOfMessageId =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReferenceAnyOfGuildId =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReferenceAnyOf =
  {
    messageId: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReferenceAnyOfMessageId;
    channelId: string;
    guildId: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReferenceAnyOfGuildId;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReference =
  GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReferenceAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItem = {
  author: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAuthor;
  id: string;
  content: string;
  createdAt: string;
  editedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEditedAt;
  pinned: boolean;
  tts: boolean;
  type: string;
  attachments: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemAttachmentsItem[];
  embeds: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemEmbedsItem[];
  mentions: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemMentions;
  reactions: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReactionsItem[];
  reference: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItemReference;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200NextCursor =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200 = {
  thread: GetApiByGuildIdBoardByBoardTypeByThreadId200Thread;
  messages: GetApiByGuildIdBoardByBoardTypeByThreadId200MessagesItem[];
  hasMore: boolean;
  nextCursor: GetApiByGuildIdBoardByBoardTypeByThreadId200NextCursor;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type getApiByGuildIdStaffResponse200 = {
  data: GetApiByGuildIdStaff200Item[];
  status: 200;
};

export type getApiByGuildIdStaffResponse422 = {
  data: GetApiByGuildIdStaff422;
  status: 422;
};

export type getApiByGuildIdStaffResponseSuccess =
  getApiByGuildIdStaffResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdStaffResponseError =
  getApiByGuildIdStaffResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdStaffResponse =
  | getApiByGuildIdStaffResponseSuccess
  | getApiByGuildIdStaffResponseError;

export const getGetApiByGuildIdStaffUrl = (guildId: string) => {
  return `/api/${guildId}/staff`;
};

export const getApiByGuildIdStaff = async (
  guildId: string,
  options?: RequestInit,
): Promise<getApiByGuildIdStaffResponse> => {
  return customFetch<getApiByGuildIdStaffResponse>(
    getGetApiByGuildIdStaffUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdNewsResponse200 = {
  data: GetApiByGuildIdNews200Item[];
  status: 200;
};

export type getApiByGuildIdNewsResponse422 = {
  data: GetApiByGuildIdNews422;
  status: 422;
};

export type getApiByGuildIdNewsResponseSuccess =
  getApiByGuildIdNewsResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdNewsResponseError =
  getApiByGuildIdNewsResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdNewsResponse =
  | getApiByGuildIdNewsResponseSuccess
  | getApiByGuildIdNewsResponseError;

export const getGetApiByGuildIdNewsUrl = (guildId: string) => {
  return `/api/${guildId}/news`;
};

export const getApiByGuildIdNews = async (
  guildId: string,
  options?: RequestInit,
): Promise<getApiByGuildIdNewsResponse> => {
  return customFetch<getApiByGuildIdNewsResponse>(
    getGetApiByGuildIdNewsUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdWidgetResponse200 = {
  data: GetApiByGuildIdWidget200;
  status: 200;
};

export type getApiByGuildIdWidgetResponse422 = {
  data: GetApiByGuildIdWidget422;
  status: 422;
};

export type getApiByGuildIdWidgetResponseSuccess =
  getApiByGuildIdWidgetResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdWidgetResponseError =
  getApiByGuildIdWidgetResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdWidgetResponse =
  | getApiByGuildIdWidgetResponseSuccess
  | getApiByGuildIdWidgetResponseError;

export const getGetApiByGuildIdWidgetUrl = (guildId: string) => {
  return `/api/${guildId}/widget`;
};

export const getApiByGuildIdWidget = async (
  guildId: string,
  options?: RequestInit,
): Promise<getApiByGuildIdWidgetResponse> => {
  return customFetch<getApiByGuildIdWidgetResponse>(
    getGetApiByGuildIdWidgetUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdBoardByBoardTypeResponse200 = {
  data: GetApiByGuildIdBoardByBoardType200Item[];
  status: 200;
};

export type getApiByGuildIdBoardByBoardTypeResponse422 = {
  data: GetApiByGuildIdBoardByBoardType422;
  status: 422;
};

export type getApiByGuildIdBoardByBoardTypeResponseSuccess =
  getApiByGuildIdBoardByBoardTypeResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdBoardByBoardTypeResponseError =
  getApiByGuildIdBoardByBoardTypeResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdBoardByBoardTypeResponse =
  | getApiByGuildIdBoardByBoardTypeResponseSuccess
  | getApiByGuildIdBoardByBoardTypeResponseError;

export const getGetApiByGuildIdBoardByBoardTypeUrl = (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
) => {
  return `/api/${guildId}/board/${boardType}`;
};

export const getApiByGuildIdBoardByBoardType = async (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
  options?: RequestInit,
): Promise<getApiByGuildIdBoardByBoardTypeResponse> => {
  return customFetch<getApiByGuildIdBoardByBoardTypeResponse>(
    getGetApiByGuildIdBoardByBoardTypeUrl(guildId, boardType),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponse200 = {
  data: GetApiByGuildIdBoardByBoardTypeByThreadId200;
  status: 200;
};

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponse422 = {
  data: GetApiByGuildIdBoardByBoardTypeByThreadId422;
  status: 422;
};

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponseSuccess =
  getApiByGuildIdBoardByBoardTypeByThreadIdResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdBoardByBoardTypeByThreadIdResponseError =
  getApiByGuildIdBoardByBoardTypeByThreadIdResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponse =
  | getApiByGuildIdBoardByBoardTypeByThreadIdResponseSuccess
  | getApiByGuildIdBoardByBoardTypeByThreadIdResponseError;

export const getGetApiByGuildIdBoardByBoardTypeByThreadIdUrl = (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
  threadId: string,
  params?: GetApiByGuildIdBoardByBoardTypeByThreadIdParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/${guildId}/board/${boardType}/${threadId}?${stringifiedParams}`
    : `/api/${guildId}/board/${boardType}/${threadId}`;
};

export const getApiByGuildIdBoardByBoardTypeByThreadId = async (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
  threadId: string,
  params?: GetApiByGuildIdBoardByBoardTypeByThreadIdParams,
  options?: RequestInit,
): Promise<getApiByGuildIdBoardByBoardTypeByThreadIdResponse> => {
  return customFetch<getApiByGuildIdBoardByBoardTypeByThreadIdResponse>(
    getGetApiByGuildIdBoardByBoardTypeByThreadIdUrl(
      guildId,
      boardType,
      threadId,
      params,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};
