/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Elysia Documentation
 * Development documentation
 * OpenAPI spec version: 0.0.0
 */
import { customFetch } from "./lib/custom-fetch";
export type GetApiByGuildIdStaff200ItemGlobalName = string | null;

export type GetApiByGuildIdStaff200ItemDiscriminator = string | null;

export type GetApiByGuildIdStaff200ItemNickname = string | null;

export type GetApiByGuildIdStaff200ItemDisplayName = string | null;

export type GetApiByGuildIdStaff200ItemAvatarUrl = string | null;

export type GetApiByGuildIdStaff200ItemGuildAvatarUrl = string | null;

export type GetApiByGuildIdStaff200ItemBannerUrl = string | null;

export type GetApiByGuildIdStaff200ItemAccentColor = number | null;

export type GetApiByGuildIdStaff200ItemAvatarDecorationUrl = string | null;

export type GetApiByGuildIdStaff200ItemFlags = string | null;

export type GetApiByGuildIdStaff200ItemRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdStaff200ItemActivity = string | null;

export type GetApiByGuildIdStaff200ItemPresenceUpdatedAt = string | null;

export type GetApiByGuildIdStaff200ItemPremiumSince = string | null;

export type GetApiByGuildIdStaff200ItemCommunicationDisabledUntil =
  | string
  | null;

export type GetApiByGuildIdStaff200ItemGuildFlags = string | null;

export type GetApiByGuildIdStaff200ItemJoinedAt = string | null;

export type GetApiByGuildIdStaff200ItemUpdatedAt = string | null;

export type GetApiByGuildIdStaff200ItemGuildUpdatedAt = string | null;

export type GetApiByGuildIdStaff200Item = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdStaff200ItemGlobalName;
  discriminator: GetApiByGuildIdStaff200ItemDiscriminator;
  nickname: GetApiByGuildIdStaff200ItemNickname;
  displayName: GetApiByGuildIdStaff200ItemDisplayName;
  bot: boolean;
  system: boolean;
  displayAvatarURL: string;
  avatarUrl: GetApiByGuildIdStaff200ItemAvatarUrl;
  guildAvatarUrl: GetApiByGuildIdStaff200ItemGuildAvatarUrl;
  bannerUrl: GetApiByGuildIdStaff200ItemBannerUrl;
  accentColor: GetApiByGuildIdStaff200ItemAccentColor;
  avatarDecorationUrl: GetApiByGuildIdStaff200ItemAvatarDecorationUrl;
  displayHexColor: string;
  flags: GetApiByGuildIdStaff200ItemFlags;
  roles: GetApiByGuildIdStaff200ItemRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdStaff200ItemActivity;
  presenceUpdatedAt: GetApiByGuildIdStaff200ItemPresenceUpdatedAt;
  pending: boolean;
  premiumSince: GetApiByGuildIdStaff200ItemPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdStaff200ItemCommunicationDisabledUntil;
  guildFlags: GetApiByGuildIdStaff200ItemGuildFlags;
  joinedAt: GetApiByGuildIdStaff200ItemJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdStaff200ItemUpdatedAt;
  guildUpdatedAt: GetApiByGuildIdStaff200ItemGuildUpdatedAt;
};

export type GetApiByGuildIdStaff422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdNews200ItemAttachmentsItem = {
  url: string;
  width: number;
  height: number;
  contentType: string;
};

export type GetApiByGuildIdNews200ItemUserAnyOfGlobalName = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfDiscriminator = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfNickname = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfDisplayName = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfAvatarUrl = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfGuildAvatarUrl = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfBannerUrl = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfAccentColor = number | null;

export type GetApiByGuildIdNews200ItemUserAnyOfAvatarDecorationUrl =
  | string
  | null;

export type GetApiByGuildIdNews200ItemUserAnyOfFlags = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdNews200ItemUserAnyOfActivity = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfPresenceUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdNews200ItemUserAnyOfPremiumSince = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfCommunicationDisabledUntil =
  | string
  | null;

export type GetApiByGuildIdNews200ItemUserAnyOfGuildFlags = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfJoinedAt = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfUpdatedAt = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOfGuildUpdatedAt = string | null;

export type GetApiByGuildIdNews200ItemUserAnyOf = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdNews200ItemUserAnyOfGlobalName;
  discriminator: GetApiByGuildIdNews200ItemUserAnyOfDiscriminator;
  nickname: GetApiByGuildIdNews200ItemUserAnyOfNickname;
  displayName: GetApiByGuildIdNews200ItemUserAnyOfDisplayName;
  bot: boolean;
  system: boolean;
  displayAvatarURL: string;
  avatarUrl: GetApiByGuildIdNews200ItemUserAnyOfAvatarUrl;
  guildAvatarUrl: GetApiByGuildIdNews200ItemUserAnyOfGuildAvatarUrl;
  bannerUrl: GetApiByGuildIdNews200ItemUserAnyOfBannerUrl;
  accentColor: GetApiByGuildIdNews200ItemUserAnyOfAccentColor;
  avatarDecorationUrl: GetApiByGuildIdNews200ItemUserAnyOfAvatarDecorationUrl;
  displayHexColor: string;
  flags: GetApiByGuildIdNews200ItemUserAnyOfFlags;
  roles: GetApiByGuildIdNews200ItemUserAnyOfRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdNews200ItemUserAnyOfActivity;
  presenceUpdatedAt: GetApiByGuildIdNews200ItemUserAnyOfPresenceUpdatedAt;
  pending: boolean;
  premiumSince: GetApiByGuildIdNews200ItemUserAnyOfPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdNews200ItemUserAnyOfCommunicationDisabledUntil;
  guildFlags: GetApiByGuildIdNews200ItemUserAnyOfGuildFlags;
  joinedAt: GetApiByGuildIdNews200ItemUserAnyOfJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdNews200ItemUserAnyOfUpdatedAt;
  guildUpdatedAt: GetApiByGuildIdNews200ItemUserAnyOfGuildUpdatedAt;
};

export type GetApiByGuildIdNews200ItemUser =
  GetApiByGuildIdNews200ItemUserAnyOf | null;

export type GetApiByGuildIdNews200Item = {
  id: string;
  content: string;
  createdAt: string;
  attachments: GetApiByGuildIdNews200ItemAttachmentsItem[];
  user: GetApiByGuildIdNews200ItemUser;
};

export type GetApiByGuildIdNews422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdWidget200MembersItemGlobalName = string | null;

export type GetApiByGuildIdWidget200MembersItemDiscriminator = string | null;

export type GetApiByGuildIdWidget200MembersItemNickname = string | null;

export type GetApiByGuildIdWidget200MembersItemDisplayName = string | null;

export type GetApiByGuildIdWidget200MembersItemAvatarUrl = string | null;

export type GetApiByGuildIdWidget200MembersItemGuildAvatarUrl = string | null;

export type GetApiByGuildIdWidget200MembersItemBannerUrl = string | null;

export type GetApiByGuildIdWidget200MembersItemAccentColor = number | null;

export type GetApiByGuildIdWidget200MembersItemAvatarDecorationUrl =
  | string
  | null;

export type GetApiByGuildIdWidget200MembersItemFlags = string | null;

export type GetApiByGuildIdWidget200MembersItemRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdWidget200MembersItemActivity = string | null;

export type GetApiByGuildIdWidget200MembersItemPresenceUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdWidget200MembersItemPremiumSince = string | null;

export type GetApiByGuildIdWidget200MembersItemCommunicationDisabledUntil =
  | string
  | null;

export type GetApiByGuildIdWidget200MembersItemGuildFlags = string | null;

export type GetApiByGuildIdWidget200MembersItemJoinedAt = string | null;

export type GetApiByGuildIdWidget200MembersItemUpdatedAt = string | null;

export type GetApiByGuildIdWidget200MembersItemGuildUpdatedAt = string | null;

export type GetApiByGuildIdWidget200MembersItem = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdWidget200MembersItemGlobalName;
  discriminator: GetApiByGuildIdWidget200MembersItemDiscriminator;
  nickname: GetApiByGuildIdWidget200MembersItemNickname;
  displayName: GetApiByGuildIdWidget200MembersItemDisplayName;
  bot: boolean;
  system: boolean;
  displayAvatarURL: string;
  avatarUrl: GetApiByGuildIdWidget200MembersItemAvatarUrl;
  guildAvatarUrl: GetApiByGuildIdWidget200MembersItemGuildAvatarUrl;
  bannerUrl: GetApiByGuildIdWidget200MembersItemBannerUrl;
  accentColor: GetApiByGuildIdWidget200MembersItemAccentColor;
  avatarDecorationUrl: GetApiByGuildIdWidget200MembersItemAvatarDecorationUrl;
  displayHexColor: string;
  flags: GetApiByGuildIdWidget200MembersItemFlags;
  roles: GetApiByGuildIdWidget200MembersItemRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdWidget200MembersItemActivity;
  presenceUpdatedAt: GetApiByGuildIdWidget200MembersItemPresenceUpdatedAt;
  pending: boolean;
  premiumSince: GetApiByGuildIdWidget200MembersItemPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdWidget200MembersItemCommunicationDisabledUntil;
  guildFlags: GetApiByGuildIdWidget200MembersItemGuildFlags;
  joinedAt: GetApiByGuildIdWidget200MembersItemJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdWidget200MembersItemUpdatedAt;
  guildUpdatedAt: GetApiByGuildIdWidget200MembersItemGuildUpdatedAt;
};

export type GetApiByGuildIdWidget200IconURL = string | null;

export type GetApiByGuildIdWidget200BannerURL = string | null;

export type GetApiByGuildIdWidget200 = {
  id: string;
  name: string;
  members: GetApiByGuildIdWidget200MembersItem[];
  presenceCount: number;
  memberCount: number;
  iconURL: GetApiByGuildIdWidget200IconURL;
  bannerURL: GetApiByGuildIdWidget200BannerURL;
};

export type GetApiByGuildIdWidget422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdBoardByBoardType200ItemBoardType =
  (typeof GetApiByGuildIdBoardByBoardType200ItemBoardType)[keyof typeof GetApiByGuildIdBoardByBoardType200ItemBoardType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiByGuildIdBoardByBoardType200ItemBoardType = {
  "job-board": "job-board",
  "dev-board": "dev-board",
  showcase: "showcase",
} as const;

export type GetApiByGuildIdBoardByBoardType200ItemMessageCount = number | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGlobalName =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfDiscriminator =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfNickname =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfDisplayName =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfAvatarUrl =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGuildAvatarUrl =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfBannerUrl =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfAccentColor =
  | number
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfAvatarDecorationUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfFlags =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfRolesItem = {
  name: string;
  position: number;
};

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfActivity =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfPresenceUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfPremiumSince =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfCommunicationDisabledUntil =
  string | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGuildFlags =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfJoinedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGuildUpdatedAt =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOf = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGlobalName;
  discriminator: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfDiscriminator;
  nickname: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfNickname;
  displayName: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfDisplayName;
  bot: boolean;
  system: boolean;
  displayAvatarURL: string;
  avatarUrl: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfAvatarUrl;
  guildAvatarUrl: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGuildAvatarUrl;
  bannerUrl: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfBannerUrl;
  accentColor: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfAccentColor;
  avatarDecorationUrl: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfAvatarDecorationUrl;
  displayHexColor: string;
  flags: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfFlags;
  roles: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfActivity;
  presenceUpdatedAt: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfPresenceUpdatedAt;
  pending: boolean;
  premiumSince: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfCommunicationDisabledUntil;
  guildFlags: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGuildFlags;
  joinedAt: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfUpdatedAt;
  guildUpdatedAt: GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOfGuildUpdatedAt;
};

export type GetApiByGuildIdBoardByBoardType200ItemAuthor =
  GetApiByGuildIdBoardByBoardType200ItemAuthorAnyOf | null;

export type GetApiByGuildIdBoardByBoardType200ItemArchived = boolean | null;

export type GetApiByGuildIdBoardByBoardType200ItemLocked = boolean | null;

export type GetApiByGuildIdBoardByBoardType200ItemCreatedAt = string | unknown;

export type GetApiByGuildIdBoardByBoardType200Item = {
  id: string;
  name: string;
  boardType: GetApiByGuildIdBoardByBoardType200ItemBoardType;
  messageCount: GetApiByGuildIdBoardByBoardType200ItemMessageCount;
  author: GetApiByGuildIdBoardByBoardType200ItemAuthor;
  archived: GetApiByGuildIdBoardByBoardType200ItemArchived;
  locked: GetApiByGuildIdBoardByBoardType200ItemLocked;
  createdAt: GetApiByGuildIdBoardByBoardType200ItemCreatedAt;
  tags: string[];
};

export type GetApiByGuildIdBoardByBoardType422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGlobalName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfDiscriminator =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfNickname =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfDisplayName =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfAvatarUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGuildAvatarUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfBannerUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfAccentColor =
  number | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfAvatarDecorationUrl =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfFlags =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfRolesItem =
  {
    name: string;
    position: number;
  };

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfActivity =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfPresenceUpdatedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfPremiumSince =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfCommunicationDisabledUntil =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGuildFlags =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfJoinedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfUpdatedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGuildUpdatedAt =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOf = {
  id: string;
  username: string;
  globalName: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGlobalName;
  discriminator: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfDiscriminator;
  nickname: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfNickname;
  displayName: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfDisplayName;
  bot: boolean;
  system: boolean;
  displayAvatarURL: string;
  avatarUrl: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfAvatarUrl;
  guildAvatarUrl: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGuildAvatarUrl;
  bannerUrl: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfBannerUrl;
  accentColor: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfAccentColor;
  avatarDecorationUrl: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfAvatarDecorationUrl;
  displayHexColor: string;
  flags: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfFlags;
  roles: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfRolesItem[];
  highestRolePosition: number;
  status: string;
  activity: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfActivity;
  presenceUpdatedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfPresenceUpdatedAt;
  pending: boolean;
  premiumSince: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfPremiumSince;
  communicationDisabledUntil: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfCommunicationDisabledUntil;
  guildFlags: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGuildFlags;
  joinedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfJoinedAt;
  createdAt: string;
  updatedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfUpdatedAt;
  guildUpdatedAt: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOfGuildUpdatedAt;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthor =
  GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthorAnyOf | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAttachmentsItemContentType =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAttachmentsItem = {
  url: string;
  name: string;
  contentType: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAttachmentsItemContentType;
  size: number;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemTitle =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemDescription =
  string | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemUrl =
  | string
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemColor =
  | number
  | null;

export type GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItem = {
  title: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemTitle;
  description: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemDescription;
  url: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemUrl;
  color: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItemColor;
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId200Item = {
  id: string;
  content: string;
  author: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAuthor;
  createdAt: string;
  attachments: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemAttachmentsItem[];
  embeds: GetApiByGuildIdBoardByBoardTypeByThreadId200ItemEmbedsItem[];
};

export type GetApiByGuildIdBoardByBoardTypeByThreadId422 = {
  type: "validation";
  on: string;
  summary?: string;
  message?: string;
  found?: unknown;
  property?: string;
  expected?: string;
};

export type getApiByGuildIdStaffResponse200 = {
  data: GetApiByGuildIdStaff200Item[];
  status: 200;
};

export type getApiByGuildIdStaffResponse422 = {
  data: GetApiByGuildIdStaff422;
  status: 422;
};

export type getApiByGuildIdStaffResponseSuccess =
  getApiByGuildIdStaffResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdStaffResponseError =
  getApiByGuildIdStaffResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdStaffResponse =
  | getApiByGuildIdStaffResponseSuccess
  | getApiByGuildIdStaffResponseError;

export const getGetApiByGuildIdStaffUrl = (guildId: string) => {
  return `/api/${guildId}/staff`;
};

export const getApiByGuildIdStaff = async (
  guildId: string,
  options?: RequestInit,
): Promise<getApiByGuildIdStaffResponse> => {
  return customFetch<getApiByGuildIdStaffResponse>(
    getGetApiByGuildIdStaffUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdNewsResponse200 = {
  data: GetApiByGuildIdNews200Item[];
  status: 200;
};

export type getApiByGuildIdNewsResponse422 = {
  data: GetApiByGuildIdNews422;
  status: 422;
};

export type getApiByGuildIdNewsResponseSuccess =
  getApiByGuildIdNewsResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdNewsResponseError =
  getApiByGuildIdNewsResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdNewsResponse =
  | getApiByGuildIdNewsResponseSuccess
  | getApiByGuildIdNewsResponseError;

export const getGetApiByGuildIdNewsUrl = (guildId: string) => {
  return `/api/${guildId}/news`;
};

export const getApiByGuildIdNews = async (
  guildId: string,
  options?: RequestInit,
): Promise<getApiByGuildIdNewsResponse> => {
  return customFetch<getApiByGuildIdNewsResponse>(
    getGetApiByGuildIdNewsUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdWidgetResponse200 = {
  data: GetApiByGuildIdWidget200;
  status: 200;
};

export type getApiByGuildIdWidgetResponse422 = {
  data: GetApiByGuildIdWidget422;
  status: 422;
};

export type getApiByGuildIdWidgetResponseSuccess =
  getApiByGuildIdWidgetResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdWidgetResponseError =
  getApiByGuildIdWidgetResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdWidgetResponse =
  | getApiByGuildIdWidgetResponseSuccess
  | getApiByGuildIdWidgetResponseError;

export const getGetApiByGuildIdWidgetUrl = (guildId: string) => {
  return `/api/${guildId}/widget`;
};

export const getApiByGuildIdWidget = async (
  guildId: string,
  options?: RequestInit,
): Promise<getApiByGuildIdWidgetResponse> => {
  return customFetch<getApiByGuildIdWidgetResponse>(
    getGetApiByGuildIdWidgetUrl(guildId),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdBoardByBoardTypeResponse200 = {
  data: GetApiByGuildIdBoardByBoardType200Item[];
  status: 200;
};

export type getApiByGuildIdBoardByBoardTypeResponse422 = {
  data: GetApiByGuildIdBoardByBoardType422;
  status: 422;
};

export type getApiByGuildIdBoardByBoardTypeResponseSuccess =
  getApiByGuildIdBoardByBoardTypeResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdBoardByBoardTypeResponseError =
  getApiByGuildIdBoardByBoardTypeResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdBoardByBoardTypeResponse =
  | getApiByGuildIdBoardByBoardTypeResponseSuccess
  | getApiByGuildIdBoardByBoardTypeResponseError;

export const getGetApiByGuildIdBoardByBoardTypeUrl = (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
) => {
  return `/api/${guildId}/board/${boardType}`;
};

export const getApiByGuildIdBoardByBoardType = async (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
  options?: RequestInit,
): Promise<getApiByGuildIdBoardByBoardTypeResponse> => {
  return customFetch<getApiByGuildIdBoardByBoardTypeResponse>(
    getGetApiByGuildIdBoardByBoardTypeUrl(guildId, boardType),
    {
      ...options,
      method: "GET",
    },
  );
};

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponse200 = {
  data: GetApiByGuildIdBoardByBoardTypeByThreadId200Item[];
  status: 200;
};

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponse422 = {
  data: GetApiByGuildIdBoardByBoardTypeByThreadId422;
  status: 422;
};

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponseSuccess =
  getApiByGuildIdBoardByBoardTypeByThreadIdResponse200 & {
    headers: Headers;
  };
export type getApiByGuildIdBoardByBoardTypeByThreadIdResponseError =
  getApiByGuildIdBoardByBoardTypeByThreadIdResponse422 & {
    headers: Headers;
  };

export type getApiByGuildIdBoardByBoardTypeByThreadIdResponse =
  | getApiByGuildIdBoardByBoardTypeByThreadIdResponseSuccess
  | getApiByGuildIdBoardByBoardTypeByThreadIdResponseError;

export const getGetApiByGuildIdBoardByBoardTypeByThreadIdUrl = (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
  threadId: string,
) => {
  return `/api/${guildId}/board/${boardType}/${threadId}`;
};

export const getApiByGuildIdBoardByBoardTypeByThreadId = async (
  guildId: string,
  boardType: "job-board" | "dev-board" | "showcase",
  threadId: string,
  options?: RequestInit,
): Promise<getApiByGuildIdBoardByBoardTypeByThreadIdResponse> => {
  return customFetch<getApiByGuildIdBoardByBoardTypeByThreadIdResponse>(
    getGetApiByGuildIdBoardByBoardTypeByThreadIdUrl(
      guildId,
      boardType,
      threadId,
    ),
    {
      ...options,
      method: "GET",
    },
  );
};
